[profile.default]
script_execution_protection = false
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
]

# Solc version
solc_version = "0.8.19"

# Optimizer settings
optimizer = true
optimizer_runs = 1000000

# EVM version
evm_version = "paris"

# Test settings
verbosity = 2
gas_reports = ["*"]

# Compiler settings
via_ir = false
bytecode_hash = "ipfs"
sparse_mode = false

# Monad Testnet RPC configuration
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

# Chain configurations
[profile.chains]
monad_testnet = { chain_id = 10143, gas_limit = 30000000 }

# Deployment profile (for broadcast)
[profile.deploy]
gas_limit = 30000000
gas_price = 1000000000  # 1 gwei

# Cache settings
cache = true
cache_path = "cache"

# (Optional) Fork settings for local testing
# Only uncomment if you actually want to fork!
# [profile.fork]
# url = "https://testnet-rpc.monad.xyz"
# block_number = "latest"




# Coverage settings
[profile.coverage]
exclude = ["test/**/*", "script/**/*"]
